if [ -z "$TMUX" ]
then
    tmux attach -t TMUX || tmux new -s TMUX > /dev/null
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
export GPG_TTY=$TTY
(( ${+commands[direnv]} )) && emulate zsh -c "$(direnv export zsh)"
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
(( ${+commands[direnv]} )) && emulate zsh -c "$(direnv hook zsh)"

plugins=(
    fzf-tab	
    git
    colorize
    zsh-autosuggestions
    zsh-syntax-highlighting
    cp
    mvn
    docker-compose
    docker 
    fzf
    kubectl
    zsh-vi-mode
)

ZVM_VI_ESCAPE_BINDKEY=jj

zstyle ':completion:*:*:make:*' tag-order 'targets'
autoload -U compinit && compinit

eval "$(direnv hook zsh)"
# User configuration

# export MANPATH="/usr/local/man:$MANPATH"
# export PATH="${go env GOPATH}/bin:$PATH"


# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
 if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 else
   export EDITOR='vim'
 fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

setopt HIST_IGNORE_SPACE

alias c=clear
alias k=kubectl
alias go="grc go"

cd() {
    if [ "$1" = "git" ]; then
        shift        # eat the 'git'
        cd ~/Documents/git > /dev/null
    else 
        builtin cd "$@"
    fi
}

# alias sops="/opt/mozilla/sops-v3.7.2.linux.amd64"
 alias nv=nvim
# alias nvim="/var/bin/nvim.appimage"

alias gita="git add . && git commit --amend -C HEAD && git push -f"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export PATH=$(go env GOPATH)/bin:$PATH

# correct terminal input
eval $(thefuck --alias)
# eval $(thefuck --alias --enable-experimental-instant-mode)
alias ff="fuck"
alias fy="fuck -y"

# Generated for envman. Do not edit.
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /home/popoffvg/go/bin/bit bit

bindkey -v
bindkey '^R' history-incremental-search-backward

# [[ -s "/home/popoffvg/.gvm/scripts/gvm" ]] && source "/home/popoffvg/.gvm/scripts/gvm"
#

