#!/usr/bin/env python3
"""Regenerate the palette catalog in main.lua from Yazi's keymap.

The palette needs a list of commands with human descriptions. Yazi has no Lua
API that reports one, but its keymap is exactly that list — every binding
carries a `run` and a `desc`. The default keymap is not installed on disk; it is
compiled into the `yazi` binary as a string, so this script reads it back out of
the binary and merges whatever the user added in ~/.config/yazi/keymap.toml.

Run it after upgrading Yazi or editing keymap.toml.
"""

import os
import re
import shutil
import sys
import tomllib
from pathlib import Path

MARKER = "#:schema https://yazi-rs.github.io/schemas/keymap.json"
LAYER = "mgr"
BEGIN = "-- BEGIN CATALOG (generated by gen-catalog.py — do not edit by hand)"
END = "-- END CATALOG"

# A line of the embedded preset: a section header, the array it opens, an entry,
# the array's closing bracket, a comment, or a blank. The first line that fits
# none of these is the unrelated binary data that follows the string.
PRESET_LINE = re.compile(r"^\s*(\[\w+\]|keymap = \[|\{ on = .*\},?|\]|#.*|)$")


def preset_keymap(binary: Path) -> dict:
	"""Read the default keymap out of the Yazi binary and parse it as TOML."""
	data = binary.read_bytes()
	start = data.find(MARKER.encode())
	if start < 0:
		sys.exit(f"{binary}: no embedded keymap found — is this a Yazi binary?")

	kept = []
	for line in data[start:].decode("utf-8", errors="replace").split("\n"):
		if not PRESET_LINE.match(line):
			break
		kept.append(line)
	return tomllib.loads("\n".join(kept))


def user_keymap() -> dict:
	path = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "yazi/keymap.toml"
	return tomllib.loads(path.read_text()) if path.is_file() else {}


def chords(keymap: dict) -> list:
	"""The bindings of one layer, in the order Yazi resolves them."""
	layer = keymap.get(LAYER, {})
	return [*layer.get("prepend_keymap", []), *layer.get("keymap", []), *layer.get("append_keymap", [])]


def catalog(binary: Path) -> list:
	"""One entry per distinct command, holding the first key bound to it."""
	seen, out = set(), []
	for chord in chords(user_keymap()) + chords(preset_keymap(binary)):
		run = chord.get("run")
		if not run:
			continue

		key = run if isinstance(run, str) else tuple(run)
		if key in seen:
			continue
		seen.add(key)

		on = chord.get("on", "")
		out.append({
			"on": on if isinstance(on, str) else "".join(on),
			"desc": chord.get("desc") or (run if isinstance(run, str) else " ; ".join(run)),
			"run": run,
		})
	return out


def lua_string(s: str) -> str:
	return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def lua_table(entries: list) -> str:
	lines = [BEGIN, "local CATALOG = {"]
	for e in entries:
		run = e["run"]
		run = lua_string(run) if isinstance(run, str) else "{ %s }" % ", ".join(lua_string(r) for r in run)
		lines.append("\t{ on = %s, desc = %s, run = %s }," % (lua_string(e["on"]), lua_string(e["desc"]), run))
	lines += ["}", END]
	return "\n".join(lines)


def main() -> None:
	yazi = shutil.which("yazi")
	if not yazi:
		sys.exit("`yazi` is not on PATH")

	entries = catalog(Path(yazi).resolve())
	main_lua = Path(__file__).with_name("main.lua")
	patched, count = re.subn(
		re.escape(BEGIN) + r".*?" + re.escape(END),
		lambda _: lua_table(entries),
		main_lua.read_text(),
		flags=re.DOTALL,
	)
	if count != 1:
		sys.exit(f"{main_lua}: expected exactly one catalog block, found {count}")

	main_lua.write_text(patched)
	print(f"{main_lua}: {len(entries)} commands")


if __name__ == "__main__":
	main()
