--- Command palette — fuzzy-find a Yazi command by its description and run it,
--- the way Ctrl-Shift-P works in Zed / VS Code.
---
--- The catalog below is generated from Yazi's own keymap by `gen-catalog.py`,
--- so the descriptions and key hints are the ones Yazi itself ships.

-- BEGIN CATALOG (generated by gen-catalog.py — do not edit by hand)
local CATALOG = {
	{ on = "<C-S-p>", desc = "Command palette", run = "plugin palette" },
	{ on = "e", desc = "Open in $EDITOR", run = "shell --block -- $EDITOR \"$@\"" },
	{ on = "T", desc = "Show or hide the preview pane", run = "plugin toggle-pane min-preview" },
	{ on = "<Esc>", desc = "Exit visual mode, clear selection, or cancel search", run = "escape" },
	{ on = "q", desc = "Quit the process", run = "quit" },
	{ on = "Q", desc = "Quit without outputting cwd-file", run = "quit --no-cwd-file" },
	{ on = "<C-c>", desc = "Close the current tab, or quit if it's last", run = "close" },
	{ on = "<C-z>", desc = "Suspend the process", run = "suspend" },
	{ on = "k", desc = "Previous file", run = "arrow prev" },
	{ on = "j", desc = "Next file", run = "arrow next" },
	{ on = "<C-u>", desc = "Move cursor up half page", run = "arrow -50%" },
	{ on = "<C-d>", desc = "Move cursor down half page", run = "arrow 50%" },
	{ on = "<C-b>", desc = "Move cursor up one page", run = "arrow -100%" },
	{ on = "<C-f>", desc = "Move cursor down one page", run = "arrow 100%" },
	{ on = "gg", desc = "Go to top", run = "arrow top" },
	{ on = "G", desc = "Go to bottom", run = "arrow bot" },
	{ on = "h", desc = "Back to the parent directory", run = "leave" },
	{ on = "l", desc = "Enter the child directory", run = "enter" },
	{ on = "H", desc = "Back to previous directory", run = "back" },
	{ on = "L", desc = "Forward to next directory", run = "forward" },
	{ on = "<Space>", desc = "Toggle the current selection state", run = { "toggle", "arrow 1" } },
	{ on = "<C-a>", desc = "Select all files", run = "toggle_all --state=on" },
	{ on = "<C-r>", desc = "Invert selection of all files", run = "toggle_all" },
	{ on = "v", desc = "Enter visual mode (selection mode)", run = "visual_mode" },
	{ on = "V", desc = "Enter visual mode (unset mode)", run = "visual_mode --unset" },
	{ on = "K", desc = "Seek up 5 units in the preview", run = "seek -5" },
	{ on = "J", desc = "Seek down 5 units in the preview", run = "seek 5" },
	{ on = "<Tab>", desc = "Spot hovered file", run = "spot" },
	{ on = "o", desc = "Open selected files", run = "open" },
	{ on = "O", desc = "Open selected files interactively", run = "open --interactive" },
	{ on = "y", desc = "Yank selected files (copy)", run = "yank" },
	{ on = "x", desc = "Yank selected files (cut)", run = "yank --cut" },
	{ on = "p", desc = "Paste yanked files", run = "paste" },
	{ on = "P", desc = "Paste yanked files (overwrite if the destination exists)", run = "paste --force" },
	{ on = "-", desc = "Symlink the absolute path of yanked files", run = "link" },
	{ on = "_", desc = "Symlink the relative path of yanked files", run = "link --relative" },
	{ on = "<C-->", desc = "Hardlink yanked files", run = "hardlink" },
	{ on = "Y", desc = "Cancel the yank status", run = "unyank" },
	{ on = "d", desc = "Trash selected files", run = "remove" },
	{ on = "D", desc = "Permanently delete selected files", run = "remove --permanently" },
	{ on = "a", desc = "Create a file (ends with / for directories)", run = "create" },
	{ on = "r", desc = "Rename selected file(s)", run = "rename --cursor=before_ext" },
	{ on = ";", desc = "Run a shell command", run = "shell --interactive" },
	{ on = ":", desc = "Run a shell command (block until finishes)", run = "shell --block --interactive" },
	{ on = ".", desc = "Toggle the visibility of hidden files", run = "hidden toggle" },
	{ on = "s", desc = "Search files by name via fd", run = "search --via=fd" },
	{ on = "S", desc = "Search files by content via ripgrep", run = "search --via=rg" },
	{ on = "<C-s>", desc = "Cancel the ongoing search", run = "escape --search" },
	{ on = "z", desc = "Jump to a file/directory via fzf", run = "plugin fzf" },
	{ on = "Z", desc = "Jump to a directory via zoxide", run = "plugin zoxide" },
	{ on = "ms", desc = "Linemode: size", run = "linemode size" },
	{ on = "mp", desc = "Linemode: permissions", run = "linemode permissions" },
	{ on = "mb", desc = "Linemode: btime", run = "linemode btime" },
	{ on = "mm", desc = "Linemode: mtime", run = "linemode mtime" },
	{ on = "mo", desc = "Linemode: owner", run = "linemode owner" },
	{ on = "mn", desc = "Linemode: none", run = "linemode none" },
	{ on = "cc", desc = "Copy file URL", run = "copy path" },
	{ on = "cd", desc = "Copy directory URL", run = "copy dirname" },
	{ on = "cf", desc = "Copy filename", run = "copy filename" },
	{ on = "cn", desc = "Copy filename without extension", run = "copy name_without_ext" },
	{ on = "f", desc = "Filter files", run = "filter --smart" },
	{ on = "/", desc = "Find next file", run = "find --smart" },
	{ on = "?", desc = "Find previous file", run = "find --previous --smart" },
	{ on = "n", desc = "Next found", run = "find_arrow" },
	{ on = "N", desc = "Previous found", run = "find_arrow --previous" },
	{ on = ",m", desc = "Sort by modified time", run = { "sort mtime --reverse=no", "linemode mtime" } },
	{ on = ",M", desc = "Sort by modified time (reverse)", run = { "sort mtime --reverse=yes", "linemode mtime" } },
	{ on = ",b", desc = "Sort by birth time", run = { "sort btime --reverse=no", "linemode btime" } },
	{ on = ",B", desc = "Sort by birth time (reverse)", run = { "sort btime --reverse=yes", "linemode btime" } },
	{ on = ",e", desc = "Sort by extension", run = "sort extension --reverse=no" },
	{ on = ",E", desc = "Sort by extension (reverse)", run = "sort extension --reverse=yes" },
	{ on = ",a", desc = "Sort alphabetically", run = "sort alphabetical --reverse=no" },
	{ on = ",A", desc = "Sort alphabetically (reverse)", run = "sort alphabetical --reverse=yes" },
	{ on = ",n", desc = "Sort naturally", run = "sort natural --reverse=no" },
	{ on = ",N", desc = "Sort naturally (reverse)", run = "sort natural --reverse=yes" },
	{ on = ",s", desc = "Sort by size", run = { "sort size --reverse=no", "linemode size" } },
	{ on = ",S", desc = "Sort by size (reverse)", run = { "sort size --reverse=yes", "linemode size" } },
	{ on = ",r", desc = "Sort randomly", run = "sort random --reverse=no" },
	{ on = "gh", desc = "Go home", run = "cd ~" },
	{ on = "gc", desc = "Go ~/.config", run = "cd ~/.config" },
	{ on = "gd", desc = "Go ~/Downloads", run = "cd ~/Downloads" },
	{ on = "g<Space>", desc = "Jump interactively", run = "cd --interactive" },
	{ on = "gf", desc = "Follow hovered symlink", run = "follow" },
	{ on = "tt", desc = "Create a new tab in CWD", run = "tab_create --current" },
	{ on = "tr", desc = "Rename current tab", run = "tab_rename --interactive" },
	{ on = "1", desc = "Switch to first tab", run = "tab_switch 0" },
	{ on = "2", desc = "Switch to second tab", run = "tab_switch 1" },
	{ on = "3", desc = "Switch to third tab", run = "tab_switch 2" },
	{ on = "4", desc = "Switch to fourth tab", run = "tab_switch 3" },
	{ on = "5", desc = "Switch to fifth tab", run = "tab_switch 4" },
	{ on = "6", desc = "Switch to sixth tab", run = "tab_switch 5" },
	{ on = "7", desc = "Switch to seventh tab", run = "tab_switch 6" },
	{ on = "8", desc = "Switch to eighth tab", run = "tab_switch 7" },
	{ on = "9", desc = "Switch to ninth tab", run = "tab_switch 8" },
	{ on = "[", desc = "Switch to previous tab", run = "tab_switch -1 --relative" },
	{ on = "]", desc = "Switch to next tab", run = "tab_switch 1 --relative" },
	{ on = "{", desc = "Swap current tab with previous tab", run = "tab_swap -1" },
	{ on = "}", desc = "Swap current tab with next tab", run = "tab_swap 1" },
	{ on = "w", desc = "Show task manager", run = "tasks:show" },
	{ on = "~", desc = "Open help", run = "help" },
}
-- END CATALOG

local function fail(content)
	ya.notify { title = "Palette", content = content, level = "error", timeout = 5 }
end

--- Render a `run` field (one command, or a chain of them) as one line of text.
local function text_of(run)
	return type(run) == "string" and run or table.concat(run, " ; ")
end

--- Split a command string into tokens, honouring quotes and backslash escapes,
--- so `shell '$EDITOR "$@"' --block` stays three tokens.
local function tokenize(s)
	local out, buf, quote = {}, nil, nil
	local i = 1
	while i <= #s do
		local c = s:sub(i, i)
		if quote then
			if c == quote then
				quote = nil
			else
				buf = (buf or "") .. c
			end
		elseif c == "'" or c == '"' then
			quote, buf = c, buf or ""
		elseif c == "\\" then
			i = i + 1
			buf = (buf or "") .. s:sub(i, i)
		elseif c:match("%s") then
			if buf then
				out[#out + 1], buf = buf, nil
			end
		else
			buf = (buf or "") .. c
		end
		i = i + 1
	end
	if buf then
		out[#out + 1] = buf
	end
	return out
end

--- Emit one command string as a Yazi action.
--- A bare `--` ends the options and hands everything after it over as one raw
--- argument, so `shell --block -- $EDITOR "$@"` stays a single shell command.
--- Only a `--` prefix marks an option — `arrow -50%` and `seek -5` pass a
--- negative positional. `ya.emit` turns an `a_b` key back into `--a-b`, so the
--- dashes in an option name have to become underscores here.
local function emit(cmd)
	local head, raw = cmd:match("^(.-)%s+%-%-%s+(.*)$")
	local tokens = tokenize(head or cmd)
	local name = table.remove(tokens, 1)
	if not name then
		return
	end

	local args = {}
	for _, t in ipairs(tokens) do
		local key, value = t:match("^%-%-([^=]+)=(.*)$")
		if key then
			args[key:gsub("%-", "_")] = value
		elseif t:sub(1, 2) == "--" then
			args[t:sub(3):gsub("%-", "_")] = true
		else
			args[#args + 1] = t
		end
	end

	args[#args + 1] = raw
	ya.emit(name, args)
end

--- Build the fzf input: one padded, coloured line per command, with the catalog
--- index in a hidden second field so the choice comes back as an exact lookup
--- instead of a re-parse of the display text.
local function lines()
	local descs, texts = {}, {}
	local wd, wt = 0, 0
	for i, c in ipairs(CATALOG) do
		descs[i], texts[i] = c.desc, text_of(c.run)
		wd = math.max(wd, #descs[i])
		wt = math.max(wt, #texts[i])
	end

	local out = {}
	for i, c in ipairs(CATALOG) do
		out[i] = string.format(
			"%s%s  \27[38;5;245m%s%s\27[0m  \27[38;5;179m%s\27[0m\t%d",
			descs[i],
			string.rep(" ", wd - #descs[i]),
			texts[i],
			string.rep(" ", wt - #texts[i]),
			c.on,
			i
		)
	end
	return table.concat(out, "\n")
end

--- Show the palette and return the chosen catalog entry, or nil if cancelled.
local function pick()
	local permit = ui.hide()
	local child, err = Command("fzf")
		:arg {
			"--delimiter=\t",
			"--with-nth=1",
			"--ansi",
			"--layout=reverse",
			"--info=inline",
			"--cycle",
			"--no-multi",
			"--prompt=Command: ",
			"--header-first",
			"--header=Enter to run · Esc to cancel",
		}
		:stdin(Command.PIPED)
		:stdout(Command.PIPED)
		:spawn()

	if not child then
		permit:drop()
		return fail(string.format("Cannot spawn `fzf`: %s", err))
	end

	child:write_all(lines())
	child:flush()

	local output, wait_err = child:wait_with_output()
	permit:drop()

	if not output then
		return fail(string.format("Cannot read `fzf` output: %s", wait_err))
	elseif not output.status.success then
		return -- 130 on Esc, and any other exit means no choice was made
	end

	local idx = tonumber(output.stdout:match("\t(%d+)%s*$"))
	return idx and CATALOG[idx]
end

return {
	entry = function()
		local chosen = pick()
		if not chosen then
			return
		elseif type(chosen.run) == "string" then
			emit(chosen.run)
		else
			for _, cmd in ipairs(chosen.run) do
				emit(cmd)
			end
		end
	end,
}
